# In _config.yml
title: Aprendizaje Automátivo
author: Fernando Crema Garcia
logo: logo.png
repository:
  url: https://github.com/ucvia/ml-book
  branch: main
execute:
  execute_notebooks: force
launch_buttons:
  colab_url: "https://colab.research.google.com"
html:
  announcement: "Beta v1.0.0: Sitio en construcción!"
  comments:
    utterances:
      repo: "ucvia/ml-book"

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib
